name: Build and Release Golang App

on:
  push:
    tags:
      - 'v*.*.*'  # El flujo de trabajo se ejecutará cuando haya un push con una etiqueta que siga el formato vX.X.X (por ejemplo, v1.0.0)

jobs:
  build:
    name: Build for AWS r6gd.medium
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, ]
        goarch: [amd64, arm]
        goarm: [""]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build binary
        env:
          GOOS: "${{ matrix.goos }}"
          GOARCH: "${{ matrix.goarch }}"
        run: |
          mkdir -p dist
          go build -o dist/compare_versions_${{ matrix.goos }}_${{ matrix.goarch }} .

      - name: Upload the Rodeo binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./dist/*
          file_glob: true
