name: Build and Release Golang App

on:
  push:
    tags:
      - 'v*.*.*'  # El flujo de trabajo se ejecutará cuando haya un push con una etiqueta que siga el formato vX.X.X (por ejemplo, v1.0.0)

jobs:
  build:
    name: Build for AWS r6gd.medium
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
        goarm: [""]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Usa la versión de Go que necesitas

      - name: Build binary
        env:
          GOOS=${{ matrix.goos }}
          GOARCH=${{ matrix.goarch }}
        run: |
          mkdir -p dist
          go build -o dist/compare_versions_${{ matrix.goos }}_${{ matrix.goarch }} .

      - name: Archive binary
        run: tar -czvf "dist/compare_versions_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz" -C dist compare_versions

      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: compare_versions-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/compare_versions_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: dist/*.tar.gz
